name: Ada Build (GPRbuild con Main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Instalar GNAT y GPRbuild
      run: |
        sudo apt-get update
        sudo apt-get install -y gnat gprbuild

    - name: Compilar Proyecto
      run: gprbuild -P colors_table.gpr
