name: Ada (SPARK Verification con Alire)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install SPARK and GNAT Toolkit via Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y gnat gprbuild gnatprove

    - name: Verify with SPARK (Level 4)
      run: gnatprove -P to_lower_string.gpr --level=4 --mode=all
